### ISSUE TITLE
Playground block not loading on my Pressable or Local sites 

### ISSUE THREAD

**Issue by westnz** [WordPress/playground-tools#168] opened 2024-02-29 22:28 UTC
I have installed and activated the Playground block on two sites: 1) Pressable and 2) Local. Unfortunately, it is not working on any of them: 

Steps: installed the plugin, opened a page, added the block...

On the Pressable site nothing happens, it just keeps saying "Preparing WordPress".
Theme: Twenty Twenty-Two
<img width="1919" alt="Screenshot 2024-03-01 at 11 18 49" src="https://github.com/WordPress/playground-tools/assets/89751452/abd0b6f5-4a19-4817-ae11-fe2dadb7b66c">

On my local site, I get an error message: "Oops! WordPress Playground had a hiccup".
Theme: Tove
<img width="1919" alt="Screenshot 2024-03-01 at 11 22 17" src="https://github.com/WordPress/playground-tools/assets/89751452/66b5391f-8558-4d8e-a1eb-72cdccc09b71">

**Comment by adamziel** [comment] 2024-03-06 15:27
@westnz Does the most recent version (0.1.8) work for you?

**Comment by westnz** [comment] 2024-03-07 16:06
Hi @adamziel 

I updated to 0.1.8 on my both the sites.

It worked on my Pressable site with the Twenty Twenty-Four theme installed, but not on my Local site with the Tove theme - same result.

**Comment by adamziel** [comment] 2024-03-07 16:18
@westnz alright, that's progress!

Is the error the same as before, that is the hiccup error message? This could mean:

* Your local site is not on HTTPS. What address does it have?
* Something is still cached in the browser – does it work in incognito mode?

Also, is there anything interesting in the developer tools (be sure to filter by "verbose")?

CC @bgrgicak

**Comment by westnz** [comment] 2024-03-09 06:50
Hey Adam

It gives the same message: Oops! WordPress Playground had a hiccup 
- Yes, it is not on HTTPS. http://travelbug.local/wp-admin/
- It didn't work in incognito mode either 

Hope this helps:
<img width="621" alt="image" src="https://github.com/WordPress/playground-tools/assets/89751452/c19c65c2-b4b2-4694-9586-949663d7e2a1">

**Comment by adamziel** [comment] 2024-03-11 12:26
Thank you @westnz! I've reproduced the problem locally – the issue is Playground can only work on either HTTPS sites, or sites served from the `localhost` domain and `http://travelbug.local` is neither. If you either add HTTPS to that site, or use  `localhost` as a domain, it should work. I'm going to close this issue for now, but if the problem prevails just say a word and I'll reopen.

Meanwhile, I adjusted the error reporting to clearly communicate what the issue is: https://github.com/WordPress/wordpress-playground/pull/1098

**Closed as completed by adamziel** 2024-03-11 12:26 UTC
Labels: Playground block, Blocker
