### ISSUE TITLE
VS Code extension: Cant open anything after updating a plugin

### ISSUE THREAD

**Issue by heyemi99** [WordPress/playground-tools#134] opened 2023-12-12 04:04 UTC
i tried to use it on visual studio code and it doesnt work anymore after updating a plugin

even trying to load a new wordpress folder it shows the same error

Warning: require_once(/var/www/html/wp-content/db.php): failed to open stream: No error information in /var/www/html/wp-includes/load.php on line 671

Fatal error: require_once(): Failed opening required '/var/www/html/wp-content/db.php' (include_path='.:') in /var/www/html/wp-includes/load.php on line 671

**Comment by adamziel** [comment] 2023-12-19 10:53
@bph had a similar problem:

> I was using the VSCode extension, and a running instance showed an update was available for SQLite Database Integration plugin, and I was offered a link to update and it ran into the error "Updated failed: Could not remove the old plugin".  continued in :thread:

![Screenshot 2023-12-11 at 14 53 34](https://github.com/WordPress/wordpress-playground/assets/205419/cd0abe2a-599e-41da-ad62-422c2f51715a)

**Comment by adamziel** [comment] 2024-02-29 12:46
cc @bgrgicak

**Comment by bgrgicak** [comment] 2024-03-01 08:34
I think that this is a wp-now issue and not a VSCode issue. 

Plugin updates fail with a message _Update failed: Could not remove the old plugin._
The old version of the plugin gets removed from the FS, but a new one is never added. I assume that this has something to do with how wp-now mounts files to sites.

In the case of the _SQLite Database Integration_ plugin after clicking update all files from `~/.wp-now/sqlite-database-integration-main` are deleted. The next time VSCode tries to start, it fails because the folder is empty. 

I was able to fix my local env by manually adding files to `~/.wp-now/sqlite-database-integration-main` [from GitHub](https://github.com/WordPress/sqlite-database-integration/archive/refs/heads/main.zip).

As a next step I will try to recreate and fix this in wp-now.

**Comment by bgrgicak** [comment] 2024-03-01 09:01
Related issue https://github.com/WordPress/playground-tools/issues/160

**Comment by adamziel** [comment] 2024-03-01 10:26
`.wp-now` tries to download the extension if it's missing in the cache, perhaps it thinks the extension is still there because an empty directory still exists?

**Comment by bgrgicak** [comment] 2024-03-01 11:14
> .wp-now tries to download the extension if it's missing in the cache, perhaps it thinks the extension is still there because an empty directory still exists?

Yes, [after adding a check if the directory is empty](https://github.com/WordPress/playground-tools/pull/169/files) files will be loaded after a server restart and the issue will be fixed.

But this won't fix the root cause. From what I understand the problem is that we are mounting a shared folder (in `.wp-now`) to all sites.
When a site wants to make changes (update) it makes changes to the shared folder. This works only partially, so a plugin update is able to remove files but unable to add files.

I think that we should copy files to site folders instead of mounting them. That way an update to one site won't affect the other site.

**Comment by bgrgicak** [comment] 2024-03-01 12:37
I updated[ the start script to copy the SQLite plugin instead of mounting the shared plugin](https://github.com/WordPress/playground-tools/pull/169/files#diff-eeed5d391a89564a5ff176b28d0ab5a31e01b94fb75f4ccc1d67f80297586595R365-R381). This will prevent single site changes from affecting the shared `.wp-now` state.

This still doesn't fix plugin updates. I assume the issue is in file permissions.

**Comment by bgrgicak** [comment] 2024-03-01 12:53
> This still doesn't fix plugin updates. I assume the issue is in file permissions.

Permissions are correct this is a problem between ` $wp_filesystem` and Playground/wp-now.
The filesystem runs an operation like delete, but ` $wp_filesystem` returns false.

**Comment by bgrgicak** [comment] 2024-03-01 13:17
I followed the delete code [from the delete_old_plugin method](https://core.trac.wordpress.org/browser/tags/6.3/src/wp-admin/includes/class-plugin-upgrader.php#L665) to see what's the root cause.

Everything works fine [until is_dir is called](https://core.trac.wordpress.org/browser/tags/6.3/src/wp-admin/includes/class-wp-filesystem-direct.php#L443) to check if `/var/www/html/wp-content/plugins/sqlite-database-integration` is a directory [on this line](https://core.trac.wordpress.org/browser/tags/6.3/src/wp-admin/includes/class-wp-filesystem-direct.php#L632).

This looks like a filesystem issue specific to wp-now or the Node version of Playground.

I will keep researching this on Monday by checking if it's happening in Node Playground.

@adamziel please let me know if you have any ideas.

**Comment by bgrgicak** [comment] 2024-03-04 11:08
I tested this in the Playground repo by adding a test to `packages/php-wasm/node/src/test/rotate-php-runtime.spec.ts`.

The test fails and if I replace the `expect` line with `console.log(php.listFiles('/test-root'));`, it returns an error.
This error is [thrown by `readdir` here](https://github.com/WordPress/wordpress-playground/blob/24f2c618c7c09d7a70e03e6a031105d39e8ac726/packages/php-wasm/universal/src/lib/base-php.ts#L746).

The same code doesn't throw an error if I disable the mount line. 

@adamziel This makes me think there is a problem with how Emscripten handles symlinks, but I don't even know where to begin with this part of the research.

### Error
```
Error:                                                                                                                │.ts
    at Object.ensureErrnoError (/Users/bero/Projects/wordpress-playground/packages/php-wasm/node/public/php_8_3.js:274│11:46:54 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
7:29)                                                                                                                 │.ts
    at Object.staticInit (/Users/bero/Projects/wordpress-playground/packages/php-wasm/node/public/php_8_3.js:2755:6)  │11:47:00 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
    at Module.init (/Users/bero/Projects/wordpress-playground/packages/php-wasm/node/public/php_8_3.js:6972:4)        │.ts
    at Module.loadPHPRuntime (/Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/load-php-r│11:47:00 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
untime.ts:128:37)                                                                                                     │.ts
    at Function.loadRuntime (/Users/bero/Projects/wordpress-playground/packages/php-wasm/node/src/lib/node-php.ts:73:1│11:47:11 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
6)                                                                                                                    │.ts
    at processTicksAndRejections (node:internal/process/task_queues:95:5)                                             │11:47:11 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
    at recreateRuntime (/Users/bero/Projects/wordpress-playground/packages/php-wasm/node/src/test/rotate-php-runtime.s│.ts
pec.ts:14:2)                                                                                                          │11:47:19 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
    at /Users/bero/Projects/wordpress-playground/packages/php-wasm/node/src/test/rotate-php-runtime.spec.ts:211:27    │.ts
    at runTest (file:///Users/bero/Projects/wordpress-playground/node_modules/@vitest/runner/dist/index.js:599:11)    │11:47:19 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
    at runSuite (file:///Users/bero/Projects/wordpress-playground/node_modules/@vitest/runner/dist/index.js:708:15) { │.ts
  node: undefined,                                                                                                    │11:47:23 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
  setErrno: [Function (anonymous)],                                                                                   │.ts
  errno: 54,                                                                                                          │11:47:23 AM [vite] page reload /Users/bero/Projects/wordpress-playground/packages/php-wasm/universal/src/lib/base-php
  message: 'FS error'                                                                                                 │.ts
} { path: '/test-root' }
```

### Test code
```
	it.only('Should read mounted files', async () => {
		const php = new NodePHP(await recreateRuntime(), {
			documentRoot: '/test-root',
		});

		const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'temp-'));
		const tempFile = path.join(tempDir, 'file');
		fs.writeFileSync(tempFile, 'playground');
		php.mkdir('/test-root');
		try {
			php.mount(tempFile, '/test-root');
			// console.log(php.listFiles('/test-root'));
			expect(php.listFiles('/test-root')).toEqual(['file']);
		} catch (e) {
			console.error(e);
		} finally {
			fs.rmSync(tempFile);
			fs.rmdirSync(tempDir);
		}
	});
```

**Comment by adamziel** [comment] 2024-03-04 11:21
> I think that we should copy files to site folders instead of mounting them. That way an update to one site won't affect the other site.

Here's a few points to consider:

* You may be starting `wp-now` in a plugin directory where there's no site. I think in that scenario the site is assembled in runtime with a core-like `mount()` directory structure?
* If you're starting wp-now in a proper WordPress site directory, `git status` would start displaying a bunch of new files coming from the SQLite integration plugin. This may or may not be okay, but I think @danielbachhuber and @sejas specifically wanted to avoid that.

Here's a question I have: what is the issue with writing to a shared directory? Other than affecting other sites, of course, which should be fine in case of the SQLite integration plugin. **Edit:** Aha, I see you explored that in follow-up comments. 👀

**Comment by adamziel** [comment] 2024-03-04 11:34
> @adamziel This makes me think there is a problem with how Emscripten handles symlinks, but I don't even know where to begin with this part of the research.

I don't think symlinks are involved. The Emscripten-built `PHP` module contains a FileSystem abstraction:

https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L1688

It consists of a tree structure for directories and mountpoints. Each mountpoint is handled by a specific backend. By default, the FS root is handled by MEMFS, where everything is based in JS objects and HEAP:

https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L805

Calling `mount()` adds a mountpoint backed by NODEFS, where operations are handled by the `require("fs")` Node module:

https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L1195

I'm not aware of comprehensive documentation around those modules. I've mostly been setting breakpoints and adding `console.log()` statements in that `php_8_2.js` file to understand the data flows and debug issues. To add to the challenge, Emscripten creates a single instance of the `FS.Error` class at one point, and then throws that pre-created instance in other places – meaning the stack trace is stripped from those errors:

https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L2750

**Comment by adamziel** [comment] 2024-03-04 11:42
I added the following console.error() statement [in the `readdir()` method of the `NODEFS` backend](https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L1373-L1381):

```diff
  readdir: node => {
   console.log("Readdir");
   var path = NODEFS.realPath(node);
   try {
    return fs.readdirSync(path);
   } catch (e) {
+    console.error(e);
    if (!e.code) throw e;
    throw new FS.ErrnoError(NODEFS.convertNodeCode(e));
   }
  },
```

And got the following output:

```
stderr | src/test/rotate-php-runtime.spec.ts > rotatePHPRuntime() > Should read mounted files
Error: ENOTDIR: not a directory, scandir '/var/folders/sb/cywb762129g3f0jzq1_p2q5h0000gp/T/temp-UtQ2yr/file'
    at Object.readdirSync (node:fs:1509:26)
    at Object.readdir (playground/packages/php-wasm/node/public/php_8_2.js:1377:15)
    at Object.readdir (playground/packages/php-wasm/node/public/php_8_2.js:2263:24)
    at _NodePHP.listFiles (playground/packages/php-wasm/universal/src/lib/base-php.ts:746:48)
    at _NodePHP.descriptor.value (playground/packages/php-wasm/universal/src/lib/rethrow-file-system-error.ts:113:19)
```

**Comment by adamziel** [comment] 2024-03-04 11:44
Aha, it makes sense – `php.mount(tempFile, '/test-root');` mounts a file, not a directory at `/test-root`. There's no way to list the files inside it. If I update that line to `php.mount(tempDir, '/test-root');` then it all works. This is consistent with the original error code 54, which [is labeled as ENOTDIR](https://github.com/WordPress/wordpress-playground/blob/2743fcc702584b473a5e59f8c6804feb22c3164f/packages/php-wasm/node/public/php_8_2.js#L7011).

**Comment by bgrgicak** [comment] 2024-03-04 11:58
I see now. In that case, this isn't related to the error we see during updates.

**Closed as completed** 2024-03-06 07:15 UTC
Labels: Bug, VS Code
