### ISSUE TITLE
`wp-now start` fails to start the local environment

### ISSUE THREAD

**Issue by michalczaplinski** [WordPress/playground-tools#5] opened 2023-05-29 11:54 UTC
It happens both on node 18 & node 14 after a fresh `npm install -g @wp-now/wp-now`. I'm using fish shell with [`fnm`](https://github.com/Schniz/fnm) so perhaps this is the culprit because of https://github.com/WordPress/playground-tools/issues/7.

```
wp-now start
/Users/czapla/.fnm/node-versions/v18.13.0/installation/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:66566
var ErrorEvent2 = class extends Event {
                                ^

ReferenceError: Event is not defined
    at Object.<anonymous> (/Users/czapla/.fnm/node-versions/v18.13.0/installation/lib/node_modules/@wp-now/wp-now/node_modules/@php-wasm/node/index.cjs:66566:33)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:183:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
    
```

**Comment by danielbachhuber** [comment] 2023-06-01 14:21
@michalczaplinski We just published a new version of `wp-now`. Can you see if the issue still reproduces?

**Comment by adamziel** [comment] 2023-06-07 21:30
Closing since that's the Node 16 issue and @michalczaplinski is on an extended leave now.

**Closed as completed** 2023-06-07 21:29 UTC
Labels: Bug, wp-now
