### ISSUE TITLE
wp-admin doesn't work without internet

### ISSUE THREAD

**Issue by cpapazoglou** [WordPress/playground-tools#74] opened 2023-06-08 12:38 UTC
While the frontpage of wordpress loads without internet, `/wp-admin` seems that it needs an internet connection. Without it, loading fails and the server gets killed.

Steps to reproduce
- In an empty folder run `wp-now start` so that wordpress gets downloaded
- Disable internet in your machine ( eg turn wifi off )
- Go to `/wp-admin`
- `ERR_CONNECTION_REFUSED`, localhost refused to connect.
- The localhost server gets killed.

```
Error: getaddrinfo ENOTFOUND api.wordpress.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'api.wordpress.org'
}
```

**Comment by danielbachhuber** [comment] 2023-06-08 12:45
Thanks for the report, @cpapazoglou !

This is a duplicate of https://github.com/WordPress/wordpress-playground/issues/535

I think php-wasm will need to be updated for this scenario. Let's continue the conversation in the first issue.

**Closed as not planned by danielbachhuber** 2023-06-08 12:45 UTC
