### ISSUE TITLE
wp-now: importFile step fails with error "DOMParser is not defined"

### ISSUE THREAD

**Issue by squelchdesign** [WordPress/playground-tools#210] opened 2024-03-31 16:14 UTC
I am running wp-now with:

```bash
wp-now start --reset --blueprint=blueprint-wp-now.json
```

My `blueprint-wp-now.json`:

```json
{
    "landingPage": "\/wp-admin\/themes.php?page=squelch-tabs-and-accordions-shortcodes",
    "preferredVersions": {
        "php": "8.1",
        "wp": "latest"
    },
    "phpExtensionBundles": [
        "kitchen-sink"
    ],
    "features": {
        "networking": true
    },
    "steps": [
        {
            "step": "defineWpConfigConsts",
            "consts": {
                "WP_DEBUG_LOG": true,
                "WP_ENVIRONMENT_TYPE": "development",
                "WP_DISABLE_FATAL_ERROR_HANDLER": true
            },
            "method": "define-before-run"
        },
        {
            "step": "installPlugin",
            "pluginZipFile": {
                "resource": "wordpress.org\/plugins",
                "slug": "font-awesome"
            },
            "options": {
                "activate": true
            }
        },
        {
            "step": "installPlugin",
            "pluginZipFile": {
                "resource": "wordpress.org\/plugins",
                "slug": "better-font-awesome"
            },
            "options": {
                "activate": true
            }
        },
        {
            "step": "installPlugin",
            "pluginZipFile": {
                "resource": "wordpress.org\/plugins",
                "slug": "block-for-font-awesome"
            },
            "options": {
                "activate": true
            }
        },
        {
            "step": "importFile",
            "file": {
                "resource": "url",
                "url": "https://github.com/squelchdesign/squelch-tabs-and-accordions-shortcodes/raw/oo-rewrite/sample-content.xml"
            }
        }
    ]
}
```

I get the following error:

```
Starting the server......
directory: /Users/lowey/devel/squelch-tabs-and-accordions-shortcodes
mode: plugin
php: 8.0
wp: latest
WordPress latest folder already exists. Skipping download.
SQLite folder already exists. Skipping download.
Created a fresh SQLite database and wp-content directory.
blueprint steps: 5
Blueprint step completed: defineWpConfigConsts
Blueprint step completed: installPlugin
Blueprint step completed: installPlugin
Blueprint step completed: installPlugin
ReferenceError: DOMParser is not defined
    at DOM (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:947:3)
    at Object.importFile (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:917:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async o (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9285:30)
    at async Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9212:23)
    at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
    at async startWPNow (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:652:5)
    at async startServer (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:970:42)
    at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25)
Error: Error when executing the blueprint step #4 ({"step":"importFile","file":{"resource":"url","url":"https://github.com/squelchdesign/squelch-tabs-and-accordions-shortcodes/raw/oo-rewrite/sample-content.xml"}}) : DOMParser is not defined
    at Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9215:37)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
    ... 2 lines matching cause stack trace ...
    at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25) {
  [cause]: ReferenceError: DOMParser is not defined
      at DOM (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:947:3)
      at Object.importFile (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:917:16)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async o (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9285:30)
      at async Object.run (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9212:23)
      at async runBlueprintSteps (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/node_modules/@wp-playground/blueprints/index.js:9320:3)
      at async startWPNow (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:652:5)
      at async startServer (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:970:42)
      at async Object.handler (file:///opt/homebrew/lib/node_modules/@wp-now/wp-now/main.js:1152:25)
}
Failed to start the server: Error when executing the blueprint step #4 ({"step":"importFile","file":{"resource":"url","url":"https://github.com/squelchdesign/squelch-tabs-and-accordions-shortcodes/raw/oo-rewrite/sample-content.xml"}}) : DOMParser is not defined
```

[The WXR import file](https://github.com/squelchdesign/squelch-tabs-and-accordions-shortcodes/blob/oo-rewrite/sample-content.xml) isn't anything fancy, it only contains a single post with some sample content so as to provide a consistent testing environment for plugin development.

#113 looked to have the same issue — although they were using a different step action — but it's been closed as fixed.

**Comment by squelchdesign** [comment] 2024-03-31 16:15
I've also just noticed that I specified PHP8.1 but wp-now is actually running 8.0…?

**Comment by squelchdesign** [comment] 2024-03-31 16:45
Ah, [#379 in wordpress-playground](https://github.com/WordPress/wordpress-playground/issues/379#issuecomment-1918729992) offers an explanation.

Feel free to close this as a duplicate if it's not helpful/needed.

**Comment by bgrgicak** [comment] 2024-04-01 07:24
This could be related to https://github.com/WordPress/wordpress-playground/issues/1157
@adamziel suggested a workaround in that issue https://github.com/WordPress/wordpress-playground/issues/1157#issuecomment-2027440383

**Comment by bgrgicak** [comment] 2024-04-01 07:28
Duplicate of https://github.com/WordPress/wordpress-playground/issues/379

**Closed as not planned by bgrgicak** 2024-04-01 07:28 UTC
