### ISSUE TITLE
custom WP REST API endpoints reply 404 when using post name permalinks

### ISSUE THREAD

**Issue by andreimirt** [WordPress/playground-tools#182] opened 2024-03-08 08:36 UTC
I am developing a plugin only for internal use that requires also the development of a small REST API.
I am using VSCode and wordpress playground extension version 0.1.56.
Everything works fine on plain permalinks if the requests are made to `http://localhost:8881/?rest_route=/plugin/v1/object`, but they fail with `404` on `http://localhost:8881/plugin/v1/object`, regardless of what the permalinks are set to, neither "post name" or "custom" works.

Initially I got into this issue using the version on the Marketplace extension (0.1.55), then I hoped the latest version in here fixes the issue, so I built it from source. Unfortunately to no avail.
I wouldn't even know where to start looking to figure what gives.
I am not even sure if this use case is supported, so perhaps it isn't supposed to work to begin with.

**Comment by adamziel** [comment] 2024-03-12 15:08
@andreimirt do you mean the issue is present in the `trunk` version of this repository? I'm asking because it seems related to https://github.com/WordPress/playground-tools/issues/53 and my first hunch is perhaps releasing a new version would solve it.

**Comment by andreimirt** [comment] 2024-03-14 10:18
Yes, I meant that the issue was present in the trunk version of the repository. and #53 was my first hunch as well, but we were both wrong. My bad, sorry, I'm new to wordpress development and although I read the documentation, I missed some essential parts. According to the documentation `http://localhost:8881/?rest_route=/plugin/v1/object`, is the equivalent of `http://localhost:8881/wp-json/plugin/v1/object`, and not `http://localhost:8881/plugin/v1/object`, mind the _wp-json_ addition. Also according to documentation the `wp-json` global namespace can be changed to something else, although it's not clear how, but it's out of scope for this issue anyway.

I just wrongly assumed that `register_rest_route('plugin/v1', '/object',...)` would register the rest route to `server/plugin/v1/object`, although the documentation is explicit about this. So my bad, there is no issue with the software, but as usual the issue was found inbetween the keyboard and the chair. This repository issue can be closed with user-DRTFM.

Anyway, adding `wp-json` to the client-side javascript requests fixes everything and everything works as expected. By the way, I'm using the vscode extension on Windows, although I noticed it's clearly mentioned that it's not tested on windows, but so far no issue.

Also, congrats on the new marketplace version, I just noticed the update. I appreciate the explicit Mode label, and that's about everything I noticed so far.

I see that I can close the issue myself, I noticed this on other repositories as well, but I don't know what's the etiquette about this. To me it feels wrong to close an issue without being a an owner/contributor of the project. What if the actual owners still need the issue for whatever reason? I wouldn't want to interfere witht their process of which outcome I'm already benefitting for free. At the same time, I can see how not closing the issue when relevant might be rude to owners/contributors. They do enough to release their work for free, they don't need to also go back to issues opened by random people on the internet only to close them, when they could have done it themselves. It's a bit like being invited to a dinner and not be willing to wash the plate you ate in. Sure, not your house, but it's free food. So would you mind sharing what would you prefer? Users closing issues when appropriate, or leaving it up to the host owners/contributors?

**Comment by adamziel** [comment] 2024-03-15 12:20
@andreimirt oh, no worries, you're welcome to close any issue you reported. Repo maintainers can always reopen if needed. For this one, I'll go ahead and close it since I'm here already.

**Closed as completed by adamziel** 2024-03-15 12:20 UTC
Labels: Bug, wp-now, VS Code
